{
  "openapi": "3.0.0",
  "info": {
    "title": "Sistema Poupou",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api-sistemapoupou.herokuapp.com"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "Users"
    },
    {
      "name": "Categories"
    },
    {
      "name": "Targets"
    },
    {
      "name": "Transaction"
    }
  ],
  "paths": {
    "/users/update-photo": {
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update photo",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "photo": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/sessions": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create Session",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "example@example.com",
                  "password": "1234567"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Eduardo Teste",
                  "email": "eduardogw061@gmail.com",
                  "password": "abcd1234"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Eduardo",
                  "email": "eduardogw061@gmail.com"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get user data",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/users/update-password": {
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update Password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "example@example.com",
                  "oldPassword": "1234567",
                  "newPassword": "abcd1234",
                  "newPasswordConfirm": "abcd1234"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/category": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "List categories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Categories"
        ],
        "summary": "Update category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "category_id": "de43c4be-c0a7-48cf-8108-293d6d6d3361",
                  "description": "Teste Editado"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Categories"
        ],
        "summary": "Delete Category",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Categories"
        ],
        "summary": "Create category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "description": "Teste",
                  "active": true,
                  "icon": "heart"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/target": {
      "post": {
        "tags": [
          "Targets"
        ],
        "summary": "Create Target",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "description": "Viagem para Paris",
                  "category_id": "5b011bc5-c6b3-4826-a596-6d2301d597ed",
                  "user_id": "6e59ee35-f761-4175-8e36-61a2c9956c10",
                  "target_amount": 10000,
                  "date_begin": "2022-10-26",
                  "date_end": "2022-11-26"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Targets"
        ],
        "summary": "Update Target",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "uuid": "27784144-fa37-4884-8e7b-a30928a21e01",
                  "description": "FÃ©rias na Bahia",
                  "category_id": "7df7d483-07f9-4e97-bc83-de536f14b86e",
                  "user_id": "6e59ee35-f761-4175-8e36-61a2c9956c10",
                  "target_amount": 75,
                  "date_begin": "2022-10-15",
                  "date_end": "2022-11-26"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Targets"
        ],
        "summary": "Delete Target",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Targets"
        ],
        "summary": "Get Targets",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "user_id",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "6e59ee35-f761-4175-8e36-61a2c9956c10"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/transaction": {
      "post": {
        "tags": [
          "Transaction"
        ],
        "summary": "Create Transaction",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "target_id": "0b1b05c8-e1da-4087-abd3-a80e1a80201b",
                  "type_id": "f0e12dd3-97b6-4a56-845a-3c3c2e6518a3",
                  "amount": 20,
                  "date": "2022-11-02"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "List Transactions",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "target_id",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "example": "0b1b05c8-e1da-4087-abd3-a80e1a80201b"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Transaction"
        ],
        "summary": "Update transaction",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "transaction_id": "ad4975fc-f3d1-49b0-b3d3-d4f0a9e0dc5e",
                  "target_id": "0b1b05c8-e1da-4087-abd3-a80e1a80201b",
                  "amount": 60,
                  "date": "2022-11-03"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Transaction"
        ],
        "summary": "Delete transaction",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}